### ISSUE TITLE
Add support for installing alpha/beta/RC builds 

### ISSUE THREAD

**Issue by beberlei** [SuoraGmbH/build-php-extension#1]
Currently the tool checks for the php versions API, which does not include alpha/beta/RC builds, such as 8.2.0rc2 currently in testing.

**Comment by rioderelfte** [comment]
With 5a6573d01c14c68d09b5e7bbc4b636f1aa51310d I added the option to pass a `--php-git-branch` instead of a `--php-version`. That way it is possible to build git tags as well. So for pre-relase versions you can either specify the current branch (`PHP-8.2`) or one of the release tags (`php-8.2.0RC4`).

**Comment by rioderelfte** [comment]
Sorry, wrong commit referenced, it was this one: d2aacdc35d518a8c96211a96f56d215ba5ec6aab
